//
// File generated by /afs/cern.ch/sw/lcg/app/releases/ROOT/5.22.00/slc4_ia32_gcc34/root/bin/rootcint at Sun Jun 21 19:39:36 2009

// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "Ana_ntupleDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
      #if !(defined(R__ACCESS_IN_SYMBOL) || defined(R__USE_SHADOW_CLASS))
      typedef ::Ana_ntuple Ana_ntuple;
      #else
      class Ana_ntuple  {
         public:
         //friend XX;
         float GenHiggs_Eta; //
         float GenHiggs_Phi; //
         float GenHiggs_Pt; //
         float GenHiggs_Mass; //
         float GenMETx; //
         float GenMETy; //
         float GenMETz; //
         float GenFJT_Eta[2]; //
         float GenFJT_Phi[2]; //
         float GenFJT_Pt[2]; //
         float GenFJT_Mass[2]; //
         int GenFJT_ID[2]; //
         float GenLepton_Eta[2]; //
         float GenLepton_Phi[2]; //
         float GenLepton_Pt[2]; //
         int GenLepton_ID[2]; //
         float GenW_Eta[2]; //
         float GenW_Phi[2]; //
         float GenW_Pt[2]; //
         float GenW_Mass[2]; //
         int S_Lepton_Num; //
         float S_Lepton_Pt[10]; //
         float S_Lepton_Eta[10]; //
         float S_Lepton_Phi[10]; //
         int S_Lepton_ID[10]; //
         float S_Lepton_Cone02[10]; //
         float S_Lepton_Cone04[10]; //
         float S_Lepton_TrkCone15[10]; //
         float S_Lepton_TrkCone30[10]; //
         float S_FJet_Pt[2]; //
         float S_FJet_Eta[2]; //
         float S_FJet_Phi[2]; //
         float S_FJet_RatioCone02[2]; //[S_FJet_Num]
         float S_FJet_RatioCone04[2]; //[S_FJet_Num]
         float S_FJet_Alpha[2]; //[S_FJet_Num]
         float S_FJet_Beta[2]; //[S_FJet_Num]
         float S_FJet_Bdis_BJet[2]; //[S_FJet_Num] only one combinedSV is used in the analysis ntuple
         int S_CJet_Num; //
         float S_CJet_Pt[10]; //[10]
         float S_CJet_Eta[10]; //[10]
         float S_CJet_Phi[10]; //[10]
         float S_CJet_RatioCone02[10]; //[10]
         float S_CJet_RatioCone04[10]; //[10]
         float S_CJet_Alpha[10]; //[10]
         float S_CJet_Beta[10]; //[10]
         float S_CJet_Bdis_BJet[10]; //[10]
         ::TFile* outputfile; //
         ::TTree* tree; //
      };
      #endif

   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void Ana_ntuple_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void Ana_ntuple_Dictionary();
   static void *new_Ana_ntuple(void *p = 0);
   static void *newArray_Ana_ntuple(Long_t size, void *p);
   static void delete_Ana_ntuple(void *p);
   static void deleteArray_Ana_ntuple(void *p);
   static void destruct_Ana_ntuple(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::Ana_ntuple*)
   {
      // Make sure the shadow class has the right sizeof
      R__ASSERT(sizeof(::Ana_ntuple) == sizeof(::ROOT::Shadow::Ana_ntuple));
      ::Ana_ntuple *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::Ana_ntuple),0);
      static ::ROOT::TGenericClassInfo 
         instance("Ana_ntuple", "Ana_ntuple.h", 16,
                  typeid(::Ana_ntuple), DefineBehavior(ptr, ptr),
                  (void*)&Ana_ntuple_ShowMembers, &Ana_ntuple_Dictionary, isa_proxy, 4,
                  sizeof(::Ana_ntuple) );
      instance.SetNew(&new_Ana_ntuple);
      instance.SetNewArray(&newArray_Ana_ntuple);
      instance.SetDelete(&delete_Ana_ntuple);
      instance.SetDeleteArray(&deleteArray_Ana_ntuple);
      instance.SetDestructor(&destruct_Ana_ntuple);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::Ana_ntuple*)
   {
      return GenerateInitInstanceLocal((::Ana_ntuple*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::Ana_ntuple*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void Ana_ntuple_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::Ana_ntuple*)0x0)->GetClass();
   }

} // end of namespace ROOT

//______________________________________________________________________________
namespace ROOT {
   void Ana_ntuple_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent)
   {
      // Inspect the data members of an object of class Ana_ntuple.
      typedef ::ROOT::Shadow::Ana_ntuple ShadowClass;
      ShadowClass *sobj = (ShadowClass*)obj;
      if (sobj) { } // Dummy usage just in case there is no datamember.

      TClass *R__cl  = ::ROOT::GenerateInitInstanceLocal((const ::Ana_ntuple*)0x0)->GetClass();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "GenHiggs_Eta", &sobj->GenHiggs_Eta);
      R__insp.Inspect(R__cl, R__parent, "GenHiggs_Phi", &sobj->GenHiggs_Phi);
      R__insp.Inspect(R__cl, R__parent, "GenHiggs_Pt", &sobj->GenHiggs_Pt);
      R__insp.Inspect(R__cl, R__parent, "GenHiggs_Mass", &sobj->GenHiggs_Mass);
      R__insp.Inspect(R__cl, R__parent, "GenMETx", &sobj->GenMETx);
      R__insp.Inspect(R__cl, R__parent, "GenMETy", &sobj->GenMETy);
      R__insp.Inspect(R__cl, R__parent, "GenMETz", &sobj->GenMETz);
      R__insp.Inspect(R__cl, R__parent, "GenFJT_Eta[2]", sobj->GenFJT_Eta);
      R__insp.Inspect(R__cl, R__parent, "GenFJT_Phi[2]", sobj->GenFJT_Phi);
      R__insp.Inspect(R__cl, R__parent, "GenFJT_Pt[2]", sobj->GenFJT_Pt);
      R__insp.Inspect(R__cl, R__parent, "GenFJT_Mass[2]", sobj->GenFJT_Mass);
      R__insp.Inspect(R__cl, R__parent, "GenFJT_ID[2]", sobj->GenFJT_ID);
      R__insp.Inspect(R__cl, R__parent, "GenLepton_Eta[2]", sobj->GenLepton_Eta);
      R__insp.Inspect(R__cl, R__parent, "GenLepton_Phi[2]", sobj->GenLepton_Phi);
      R__insp.Inspect(R__cl, R__parent, "GenLepton_Pt[2]", sobj->GenLepton_Pt);
      R__insp.Inspect(R__cl, R__parent, "GenLepton_ID[2]", sobj->GenLepton_ID);
      R__insp.Inspect(R__cl, R__parent, "GenW_Eta[2]", sobj->GenW_Eta);
      R__insp.Inspect(R__cl, R__parent, "GenW_Phi[2]", sobj->GenW_Phi);
      R__insp.Inspect(R__cl, R__parent, "GenW_Pt[2]", sobj->GenW_Pt);
      R__insp.Inspect(R__cl, R__parent, "GenW_Mass[2]", sobj->GenW_Mass);
      R__insp.Inspect(R__cl, R__parent, "S_Lepton_Num", &sobj->S_Lepton_Num);
      R__insp.Inspect(R__cl, R__parent, "S_Lepton_Pt[10]", sobj->S_Lepton_Pt);
      R__insp.Inspect(R__cl, R__parent, "S_Lepton_Eta[10]", sobj->S_Lepton_Eta);
      R__insp.Inspect(R__cl, R__parent, "S_Lepton_Phi[10]", sobj->S_Lepton_Phi);
      R__insp.Inspect(R__cl, R__parent, "S_Lepton_ID[10]", sobj->S_Lepton_ID);
      R__insp.Inspect(R__cl, R__parent, "S_Lepton_Cone02[10]", sobj->S_Lepton_Cone02);
      R__insp.Inspect(R__cl, R__parent, "S_Lepton_Cone04[10]", sobj->S_Lepton_Cone04);
      R__insp.Inspect(R__cl, R__parent, "S_Lepton_TrkCone15[10]", sobj->S_Lepton_TrkCone15);
      R__insp.Inspect(R__cl, R__parent, "S_Lepton_TrkCone30[10]", sobj->S_Lepton_TrkCone30);
      R__insp.Inspect(R__cl, R__parent, "S_FJet_Pt[2]", sobj->S_FJet_Pt);
      R__insp.Inspect(R__cl, R__parent, "S_FJet_Eta[2]", sobj->S_FJet_Eta);
      R__insp.Inspect(R__cl, R__parent, "S_FJet_Phi[2]", sobj->S_FJet_Phi);
      R__insp.Inspect(R__cl, R__parent, "S_FJet_RatioCone02[2]", sobj->S_FJet_RatioCone02);
      R__insp.Inspect(R__cl, R__parent, "S_FJet_RatioCone04[2]", sobj->S_FJet_RatioCone04);
      R__insp.Inspect(R__cl, R__parent, "S_FJet_Alpha[2]", sobj->S_FJet_Alpha);
      R__insp.Inspect(R__cl, R__parent, "S_FJet_Beta[2]", sobj->S_FJet_Beta);
      R__insp.Inspect(R__cl, R__parent, "S_FJet_Bdis_BJet[2]", sobj->S_FJet_Bdis_BJet);
      R__insp.Inspect(R__cl, R__parent, "S_CJet_Num", &sobj->S_CJet_Num);
      R__insp.Inspect(R__cl, R__parent, "S_CJet_Pt[10]", sobj->S_CJet_Pt);
      R__insp.Inspect(R__cl, R__parent, "S_CJet_Eta[10]", sobj->S_CJet_Eta);
      R__insp.Inspect(R__cl, R__parent, "S_CJet_Phi[10]", sobj->S_CJet_Phi);
      R__insp.Inspect(R__cl, R__parent, "S_CJet_RatioCone02[10]", sobj->S_CJet_RatioCone02);
      R__insp.Inspect(R__cl, R__parent, "S_CJet_RatioCone04[10]", sobj->S_CJet_RatioCone04);
      R__insp.Inspect(R__cl, R__parent, "S_CJet_Alpha[10]", sobj->S_CJet_Alpha);
      R__insp.Inspect(R__cl, R__parent, "S_CJet_Beta[10]", sobj->S_CJet_Beta);
      R__insp.Inspect(R__cl, R__parent, "S_CJet_Bdis_BJet[10]", sobj->S_CJet_Bdis_BJet);
      R__insp.Inspect(R__cl, R__parent, "*outputfile", &sobj->outputfile);
      R__insp.Inspect(R__cl, R__parent, "*tree", &sobj->tree);
   }

}

namespace ROOT {
   // Wrappers around operator new
   static void *new_Ana_ntuple(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::Ana_ntuple : new ::Ana_ntuple;
   }
   static void *newArray_Ana_ntuple(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::Ana_ntuple[nElements] : new ::Ana_ntuple[nElements];
   }
   // Wrapper around operator delete
   static void delete_Ana_ntuple(void *p) {
      delete ((::Ana_ntuple*)p);
   }
   static void deleteArray_Ana_ntuple(void *p) {
      delete [] ((::Ana_ntuple*)p);
   }
   static void destruct_Ana_ntuple(void *p) {
      typedef ::Ana_ntuple current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::Ana_ntuple

/********************************************************
* Ana_ntupleDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && (__GNUC__ > 3) && (__GNUC_MINOR__ > 1)
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableAna_ntupleDict();

extern "C" void G__set_cpp_environmentAna_ntupleDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("Ana_ntuple.h");
  G__cpp_reset_tagtableAna_ntupleDict();
}
#include <new>
extern "C" int G__cpp_dllrevAna_ntupleDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* Ana_ntuple */
static int G__Ana_ntupleDict_522_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   Ana_ntuple* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new Ana_ntuple[n];
     } else {
       p = new((void*) gvp) Ana_ntuple[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new Ana_ntuple;
     } else {
       p = new((void*) gvp) Ana_ntuple;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__Ana_ntupleDictLN_Ana_ntuple));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Ana_ntupleDict_522_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Ana_ntuple*) G__getstructoffset())->close();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Ana_ntupleDict_522_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Ana_ntuple*) G__getstructoffset())->fill();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Ana_ntupleDict_522_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Ana_ntuple*) G__getstructoffset())->new_event();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Ana_ntupleDict_522_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Ana_ntuple*) G__getstructoffset())->add_G_Higgs((float) G__double(libp->para[0]), (float) G__double(libp->para[1])
, (float) G__double(libp->para[2]), (float) G__double(libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Ana_ntupleDict_522_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Ana_ntuple*) G__getstructoffset())->add_G_METx((float) G__double(libp->para[0]), (float) G__double(libp->para[1])
, (float) G__double(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Ana_ntupleDict_522_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Ana_ntuple*) G__getstructoffset())->add_G_FJT(
(float) G__double(libp->para[0]), (float) G__double(libp->para[1])
, (float) G__double(libp->para[2]), (float) G__double(libp->para[3])
, (int) G__int(libp->para[4]), (float) G__double(libp->para[5])
, (float) G__double(libp->para[6]), (float) G__double(libp->para[7])
, (float) G__double(libp->para[8]), (int) G__int(libp->para[9]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Ana_ntupleDict_522_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Ana_ntuple*) G__getstructoffset())->add_G_Lep(
(float) G__double(libp->para[0]), (float) G__double(libp->para[1])
, (float) G__double(libp->para[2]), (int) G__int(libp->para[3])
, (float) G__double(libp->para[4]), (float) G__double(libp->para[5])
, (float) G__double(libp->para[6]), (int) G__int(libp->para[7]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Ana_ntupleDict_522_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Ana_ntuple*) G__getstructoffset())->add_G_W(
(float) G__double(libp->para[0]), (float) G__double(libp->para[1])
, (float) G__double(libp->para[2]), (int) G__int(libp->para[3])
, (float) G__double(libp->para[4]), (float) G__double(libp->para[5])
, (float) G__double(libp->para[6]), (int) G__int(libp->para[7]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Ana_ntupleDict_522_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Ana_ntuple*) G__getstructoffset())->add_S_Lep(
(float) G__double(libp->para[0]), (float) G__double(libp->para[1])
, (float) G__double(libp->para[2]), (int) G__int(libp->para[3])
, (float) G__double(libp->para[4]), (float) G__double(libp->para[5])
, (float) G__double(libp->para[6]), (float) G__double(libp->para[7]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Ana_ntupleDict_522_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Ana_ntuple*) G__getstructoffset())->add_S_FJT(
(float) G__double(libp->para[0]), (float) G__double(libp->para[1])
, (float) G__double(libp->para[2]), (float) G__double(libp->para[3])
, (float) G__double(libp->para[4]), (float) G__double(libp->para[5])
, (float) G__double(libp->para[6]), (float) G__double(libp->para[7])
, (float) G__double(libp->para[8]), (float) G__double(libp->para[9])
, (float) G__double(libp->para[10]), (float) G__double(libp->para[11])
, (float) G__double(libp->para[12]), (float) G__double(libp->para[13])
, (float) G__double(libp->para[14]), (float) G__double(libp->para[15]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Ana_ntupleDict_522_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Ana_ntuple*) G__getstructoffset())->add_S_CJet(
(float) G__double(libp->para[0]), (float) G__double(libp->para[1])
, (float) G__double(libp->para[2]), (float) G__double(libp->para[3])
, (float) G__double(libp->para[4]), (float) G__double(libp->para[5])
, (float) G__double(libp->para[6]), (float) G__double(libp->para[7]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__Ana_ntupleDict_522_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   Ana_ntuple* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new Ana_ntuple(*(Ana_ntuple*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__Ana_ntupleDictLN_Ana_ntuple));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef Ana_ntuple G__TAna_ntuple;
static int G__Ana_ntupleDict_522_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (Ana_ntuple*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((Ana_ntuple*) (soff+(sizeof(Ana_ntuple)*i)))->~G__TAna_ntuple();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (Ana_ntuple*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((Ana_ntuple*) (soff))->~G__TAna_ntuple();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__Ana_ntupleDict_522_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   Ana_ntuple* dest = (Ana_ntuple*) G__getstructoffset();
   *dest = *(Ana_ntuple*) libp->para[0].ref;
   const Ana_ntuple& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* Ana_ntuple */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncAna_ntupleDict {
 public:
  G__Sizep2memfuncAna_ntupleDict(): p(&G__Sizep2memfuncAna_ntupleDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncAna_ntupleDict::*p)();
};

size_t G__get_sizep2memfuncAna_ntupleDict()
{
  G__Sizep2memfuncAna_ntupleDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceAna_ntupleDict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableAna_ntupleDict() {

   /* Setting up typedef entry */
   G__search_typename2("vector<TSchemaHelper>",117,G__get_linked_tagnum(&G__Ana_ntupleDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__Ana_ntupleDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Ana_ntupleDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__Ana_ntupleDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Ana_ntupleDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__Ana_ntupleDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__Ana_ntupleDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__Ana_ntupleDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__Ana_ntupleDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__Ana_ntupleDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__Ana_ntupleDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__Ana_ntupleDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__Ana_ntupleDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__Ana_ntupleDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string>>",117,G__get_linked_tagnum(&G__Ana_ntupleDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* Ana_ntuple */
static void G__setup_memvarAna_ntuple(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__Ana_ntupleDictLN_Ana_ntuple));
   { Ana_ntuple *p; p=(Ana_ntuple*)0x1000; if (p) { }
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"GenHiggs_Eta=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"GenHiggs_Phi=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"GenHiggs_Pt=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"GenHiggs_Mass=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"GenMETx=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"GenMETy=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"GenMETz=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"GenFJT_Eta[2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"GenFJT_Phi[2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"GenFJT_Pt[2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"GenFJT_Mass[2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"GenFJT_ID[2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"GenLepton_Eta[2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"GenLepton_Phi[2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"GenLepton_Pt[2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"GenLepton_ID[2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"GenW_Eta[2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"GenW_Phi[2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"GenW_Pt[2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"GenW_Mass[2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"S_Lepton_Num=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"S_Lepton_Pt[10]=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"S_Lepton_Eta[10]=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"S_Lepton_Phi[10]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"S_Lepton_ID[10]=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"S_Lepton_Cone02[10]=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"S_Lepton_Cone04[10]=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"S_Lepton_TrkCone15[10]=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"S_Lepton_TrkCone30[10]=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"S_FJet_Pt[2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"S_FJet_Eta[2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"S_FJet_Phi[2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"S_FJet_RatioCone02[2]=",0,"[S_FJet_Num]");
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"S_FJet_RatioCone04[2]=",0,"[S_FJet_Num]");
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"S_FJet_Alpha[2]=",0,"[S_FJet_Num]");
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"S_FJet_Beta[2]=",0,"[S_FJet_Num]");
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"S_FJet_Bdis_BJet[2]=",0,"[S_FJet_Num] only one combinedSV is used in the analysis ntuple");
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"S_CJet_Num=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"S_CJet_Pt[10]=",0,"[10]");
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"S_CJet_Eta[10]=",0,"[10]");
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"S_CJet_Phi[10]=",0,"[10]");
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"S_CJet_RatioCone02[10]=",0,"[10]");
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"S_CJet_RatioCone04[10]=",0,"[10]");
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"S_CJet_Alpha[10]=",0,"[10]");
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"S_CJet_Beta[10]=",0,"[10]");
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"S_CJet_Bdis_BJet[10]=",0,"[10]");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__Ana_ntupleDictLN_TFile),-1,-1,4,"outputfile=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__Ana_ntupleDictLN_TTree),-1,-1,4,"tree=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarAna_ntupleDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncAna_ntuple(void) {
   /* Ana_ntuple */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__Ana_ntupleDictLN_Ana_ntuple));
   G__memfunc_setup("Ana_ntuple",1031,G__Ana_ntupleDict_522_0_1, 105, G__get_linked_tagnum(&G__Ana_ntupleDictLN_Ana_ntuple), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("close",534,G__Ana_ntupleDict_522_0_2, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("fill",423,G__Ana_ntupleDict_522_0_3, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("new_event",971,G__Ana_ntupleDict_522_0_4, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("add_G_Higgs",1056,G__Ana_ntupleDict_522_0_5, 121, -1, -1, 0, 4, 1, 1, 0, 
"f - - 0 - pt f - - 0 - eta "
"f - - 0 - phi f - - 0 - mass", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("add_G_METx",908,G__Ana_ntupleDict_522_0_6, 121, -1, -1, 0, 3, 1, 1, 0, 
"f - - 0 - metx f - - 0 - mety "
"f - - 0 - metz", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("add_G_FJT",786,G__Ana_ntupleDict_522_0_7, 121, -1, -1, 0, 10, 1, 1, 0, 
"f - - 0 - pt0 f - - 0 - eta0 "
"f - - 0 - phi0 f - - 0 - mass0 "
"i - - 0 - id0 f - - 0 - pt1 "
"f - - 0 - eta1 f - - 0 - phi1 "
"f - - 0 - mass1 i - - 0 - id1", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("add_G_Lep",847,G__Ana_ntupleDict_522_0_8, 121, -1, -1, 0, 8, 1, 1, 0, 
"f - - 0 - pt0 f - - 0 - eta0 "
"f - - 0 - phi0 i - - 0 - id0 "
"f - - 0 - pt1 f - - 0 - eta1 "
"f - - 0 - phi1 i - - 0 - id1", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("add_G_W",645,G__Ana_ntupleDict_522_0_9, 121, -1, -1, 0, 8, 1, 1, 0, 
"f - - 0 - pt0 f - - 0 - eta0 "
"f - - 0 - phi0 i - - 0 - mass0 "
"f - - 0 - pt1 f - - 0 - eta1 "
"f - - 0 - phi1 i - - 0 - mass1", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("add_S_Lep",859,G__Ana_ntupleDict_522_0_10, 121, -1, -1, 0, 8, 1, 1, 0, 
"f - - 0 - pt f - - 0 - eta "
"f - - 0 - phi i - - 0 - id "
"f - - 0 - cone02 f - - 0 - cone04 "
"f - - 0 - trkcone15 f - - 0 - trkcone30", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("add_S_FJT",798,G__Ana_ntupleDict_522_0_11, 121, -1, -1, 0, 16, 1, 1, 0, 
"f - - 0 - pt0 f - - 0 - eta0 "
"f - - 0 - phi0 f - - 0 - cone020 "
"f - - 0 - cone040 f - - 0 - alpha0 "
"f - - 0 - beta0 f - - 0 - btag0 "
"f - - 0 - pt1 f - - 0 - eta1 "
"f - - 0 - phi1 f - - 0 - cone021 "
"f - - 0 - cone041 f - - 0 - alpha1 "
"f - - 0 - beta1 f - - 0 - btag1", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("add_S_CJet",928,G__Ana_ntupleDict_522_0_12, 121, -1, -1, 0, 8, 1, 1, 0, 
"f - - 0 - pt f - - 0 - eta "
"f - - 0 - phi f - - 0 - cone02 "
"f - - 0 - cone04 f - - 0 - alpha "
"f - - 0 - beta f - - 0 - btag", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("Ana_ntuple", 1031, G__Ana_ntupleDict_522_0_13, (int) ('i'), G__get_linked_tagnum(&G__Ana_ntupleDictLN_Ana_ntuple), -1, 0, 1, 1, 1, 0, "u 'Ana_ntuple' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~Ana_ntuple", 1157, G__Ana_ntupleDict_522_0_14, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__Ana_ntupleDict_522_0_15, (int) ('u'), G__get_linked_tagnum(&G__Ana_ntupleDictLN_Ana_ntuple), -1, 1, 1, 1, 1, 0, "u 'Ana_ntuple' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncAna_ntupleDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalAna_ntupleDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcAna_ntupleDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__Ana_ntupleDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__Ana_ntupleDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__Ana_ntupleDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__Ana_ntupleDictLN_TFile = { "TFile" , 99 , -1 };
G__linked_taginfo G__Ana_ntupleDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__Ana_ntupleDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__Ana_ntupleDictLN_TTree = { "TTree" , 99 , -1 };
G__linked_taginfo G__Ana_ntupleDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__Ana_ntupleDictLN_Ana_ntuple = { "Ana_ntuple" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableAna_ntupleDict() {
  G__Ana_ntupleDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__Ana_ntupleDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__Ana_ntupleDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__Ana_ntupleDictLN_TFile.tagnum = -1 ;
  G__Ana_ntupleDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__Ana_ntupleDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__Ana_ntupleDictLN_TTree.tagnum = -1 ;
  G__Ana_ntupleDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__Ana_ntupleDictLN_Ana_ntuple.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableAna_ntupleDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__Ana_ntupleDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__Ana_ntupleDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__Ana_ntupleDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__Ana_ntupleDictLN_TFile);
   G__get_linked_tagnum_fwd(&G__Ana_ntupleDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Ana_ntupleDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__Ana_ntupleDictLN_TTree);
   G__get_linked_tagnum_fwd(&G__Ana_ntupleDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__tagtable_setup(G__get_linked_tagnum(&G__Ana_ntupleDictLN_Ana_ntuple),sizeof(Ana_ntuple),-1,263424,(char*)NULL,G__setup_memvarAna_ntuple,G__setup_memfuncAna_ntuple);
}
extern "C" void G__cpp_setupAna_ntupleDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupAna_ntupleDict()");
  G__set_cpp_environmentAna_ntupleDict();
  G__cpp_setup_tagtableAna_ntupleDict();

  G__cpp_setup_inheritanceAna_ntupleDict();

  G__cpp_setup_typetableAna_ntupleDict();

  G__cpp_setup_memvarAna_ntupleDict();

  G__cpp_setup_memfuncAna_ntupleDict();
  G__cpp_setup_globalAna_ntupleDict();
  G__cpp_setup_funcAna_ntupleDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncAna_ntupleDict();
  return;
}
class G__cpp_setup_initAna_ntupleDict {
  public:
    G__cpp_setup_initAna_ntupleDict() { G__add_setup_func("Ana_ntupleDict",(G__incsetup)(&G__cpp_setupAna_ntupleDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initAna_ntupleDict() { G__remove_setup_func("Ana_ntupleDict"); }
};
G__cpp_setup_initAna_ntupleDict G__cpp_setup_initializerAna_ntupleDict;

