/********************************************************************
* Ana_ntupleDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error Ana_ntupleDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "cint/G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableAna_ntupleDict();
extern void G__cpp_setup_inheritanceAna_ntupleDict();
extern void G__cpp_setup_typetableAna_ntupleDict();
extern void G__cpp_setup_memvarAna_ntupleDict();
extern void G__cpp_setup_globalAna_ntupleDict();
extern void G__cpp_setup_memfuncAna_ntupleDict();
extern void G__cpp_setup_funcAna_ntupleDict();
extern void G__set_cpp_environmentAna_ntupleDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Ana_ntuple.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__Ana_ntupleDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__Ana_ntupleDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Ana_ntupleDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__Ana_ntupleDictLN_TFile;
extern G__linked_taginfo G__Ana_ntupleDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__Ana_ntupleDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__Ana_ntupleDictLN_TTree;
extern G__linked_taginfo G__Ana_ntupleDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__Ana_ntupleDictLN_Ana_ntuple;

/* STUB derived class for protected member access */
